import localFont  from "next/font/local"
import "./globals.css";
import Navbar from "@/components/navbar";
import 'leaflet/dist/leaflet.css';



const sathoshi = localFont({
  src : [
    {
      path : "./fonts/Satoshi-Medium.ttf",
      weight: "700"
    },
    {
      path : "./fonts/Satoshi-Regular.ttf",
      weight: "500"
    },
    {
      path : "./fonts/Satoshi-Bold.ttf",
      weight: "900"
    },
    {
      path : "./fonts/Satoshi-Light.ttf",
      weight: "400"
    }
  ],
})

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${sathoshi.className} antialiased `}
      >
        <div className="absolute w-screen">
          <Navbar/>
        </div>
        {children}
      </body>
    </html>
  );
}
